## Dockerfile for Jupyter GMT Convenience Image
##
ARG GMT_PYTHON_DOCKER_TAG=python
FROM nc5ng/gmt:$GMT_PYTHON_DOCKER_TAG

LABEL maintainer="akshmakov@nc5ng.org"
	    
COPY requirements-jupyter.txt /requirements-jupyter.txt

COPY ./Example.ipynb /workspace

RUN pip3 install -r /requirements-jupyter.txt 

ENTRYPOINT [ "/usr/local/bin/jupyter" ]

CMD [ "notebook",  "--allow-root" , "--port=8888", "--ip=0.0.0.0" ]

